### PR TITLE
Disable composition in bulk upload

### PR DESCRIPTION
**Pull request by sibayanjasper**

### CODE REVIEW

**Comment by ravenjohn** [comment]
<a href="http://ninja.raven.tm/anyTV/music-dashboard/pull/386" target="_blank">ReviewNinja

**Comment by ravenjohn** [comment]
<a href="http://ninja.raven.tm/anyTV/music-dashboard/pull/386" target="_blank">ReviewNinja

**Comment by sibayanjasper** [comment]
Test #Tunes-72 tag ReqTechReview

**Comment by pprmint** [comment]
:+1:

**Comment by sibayanjasper** [comment]
:+1:

**Comment by jvmsangkal** [comment]
:+1:

**Pull request merged**
