### PR TITLE
add loading indicator and search for asset title in earnings

### PR DESCRIPTION
**Pull request by jvmsangkal**

### CODE REVIEW

**Comment by ravenjohn** [comment]
<a href="http://ninja.raven.tm/anyTV/music-dashboard/pull/387" target="_blank">ReviewNinja

**Comment by ravenjohn** [comment]
<a href="http://ninja.raven.tm/anyTV/music-dashboard/pull/387" target="_blank">ReviewNinja

**Comment by sibayanjasper** [comment]
:+1:

**Comment by jvmsangkal** [comment]
:star:

**Pull request merged**
