### PR TITLE
fix 403 page when user is not logged in

### PR DESCRIPTION
**Pull request by jvmsangkal**

### CODE REVIEW

**Comment by ravenjohn** [comment]
<a href="http://ninja.raven.tm/anyTV/music-dashboard/pull/392" target="_blank">ReviewNinja

**Comment by rycastaneda** [comment]
:AllenApproves:

**Comment by rycastaneda** [comment]
:star:

**Comment by jvmsangkal** [comment]
:AllenApproves:

**Comment by rycastaneda** [comment]
:AllenApproves:

**Pull request merged**
