### PR TITLE
change implementation of getting items

### PR DESCRIPTION
**Pull request by rycastaneda**

### CODE REVIEW

**Comment by ravenjohn** [comment]
<a href="http://ninja.raven.tm/anyTV/music-dashboard/pull/407" target="_blank">ReviewNinja

**Comment by jvmsangkal** [comment]
:AllenApproves:

**Comment by ravenjohn** [comment]
@rycastaneda @jvmsangkal @pprmint @cedricabuso I thought review ninja should be removed on the code review pipeline since passing review board is considered enough?

**Comment by cedricabuso** [comment]
@ravenjohn Ahh. Yes. Sorry, haven't removed review ninja on the repos yet.

**Comment by ravenjohn** [comment]
@cedricabuso oke. I removed it for you bro

**Comment by cedricabuso** [comment]
@ravenjohn Thanks, mate!

**Comment by jvmsangkal** [comment]
Review board link: http://reviewboard.freedom.tm/r/116/diff/1#index_header

**Pull request merged**
