### PR TITLE
fix edit artist for MP

### PR DESCRIPTION
**Pull request by jvmsangkal**

### CODE REVIEW

**Comment by ravenjohn** [comment]
<a href="http://ninja.raven.tm/anyTV/music-dashboard/pull/381" target="_blank">ReviewNinja

**Comment by ravenjohn** [comment]
<a href="http://ninja.raven.tm/anyTV/music-dashboard/pull/381" target="_blank">ReviewNinja

**Comment by sibayanjasper** [comment]
:+1:

**Comment by rycastaneda** [comment]
:+1:

**Pull request merged**
