### PR TITLE
fix enter pressing behavior on filters

### PR DESCRIPTION
**Pull request by jvmsangkal**

### CODE REVIEW

**Comment by ravenjohn** [comment]
<a href="http://ninja.raven.tm/anyTV/music-dashboard/pull/388" target="_blank">ReviewNinja

**Comment by ravenjohn** [comment]
<a href="http://ninja.raven.tm/anyTV/music-dashboard/pull/388" target="_blank">ReviewNinja

**Comment by sibayanjasper** [comment]
:+1:

**Comment by jvmsangkal** [comment]
:star:

**Comment by sibayanjasper** [comment]
:+1:

**Pull request merged**
