### PR TITLE
fix pagination on manage albums as music provider

### PR DESCRIPTION
**Pull request by jvmsangkal**

### CODE REVIEW

**Comment by ravenjohn** [comment]
<a href="http://ninja.raven.tm/anyTV/music-dashboard/pull/383" target="_blank">ReviewNinja

**Comment by ravenjohn** [comment]
<a href="http://ninja.raven.tm/anyTV/music-dashboard/pull/383" target="_blank">ReviewNinja

**Comment by sibayanjasper** [comment]
:+1:

**Comment by sibayanjasper** [comment]
:+1:

**Comment by rycastaneda** [comment]
:+1:

**Comment by sibayanjasper** [comment]
:+1:

**Comment by jvmsangkal** [comment]
:star:

**Pull request merged**
